print ("Please enter your name")
yourname =input ()
print ("What is your age?")
age =int(input ())
print ("What is your favorite TV programme?")
programme=input ()
print()
print (yourname)
print("is")
print (age)
print("years old and likes")
print (programme)