yourname =input ( "Please enter your name\n ")
age =int (input  ("What is your age?\n "))
programme=input ("What is your favorite TV programme?\n ")
print (yourname,age)
print ("likes watching",programme)
